gitapiVersion: apps/v1
kind: Deployment
metadata:
  name: residenceallocationsystem #name of the app
spec:
  replicas: 2 #run 2 pods or 2 docker images and 2pods
  selector:
    matchLabels:
      app: residenceallocationsystem
  template:
    metadata:
      labels:
        app: residenceallocationsystem
  
    spec:
      containers:
      - name: residenceallocationsystem
        image: residenceallocationsystem/ras        
        ports:
        - containerPort: 80
      
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: azure-vote-front
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: azure-vote-front